<!-- JS Scripts -->
<script src="{{ asset('assets/js/custom.js') }} "></script>
<script src="{{ asset('js/app.js') }} "></script>
<script src="{{ asset('assets/js/jquery.appear.js') }}"></script>
<script src="{{ asset('assets/js/jquery.mousewheel.js') }}"></script>
<script src="{{ asset('assets/js/perfect-scrollbar.js') }}"></script>
<script src="{{ asset('assets/js/jquery.matchHeight.js') }}"></script>
<script src="{{ asset('assets/js/svgxuse.js') }}"></script>
<script src="{{ asset('assets/js/imagesloaded.pkgd.js') }}"></script>
<script src="{{ asset('assets/js/Headroom.js') }}"></script>
<script src="{{ asset('assets/js/velocity.js') }}"></script>
<script src="{{ asset('assets/js/ScrollMagic.js') }}"></script>
<script src="{{ asset('assets/js/jquery.waypoints.js') }}"></script>
<script src="{{ asset('assets/js/jquery.countTo.js') }}"></script>
<script src="{{ asset('assets/js/popper.min.js') }}"></script>
<script src="{{ asset('assets/js/material.min.js') }}"></script>
<script src="{{ asset('assets/js/bootstrap-select.js') }}"></script>
<script src="{{ asset('assets/js/smooth-scroll.js') }}"></script>
<script src="{{ asset('assets/js/selectize.js') }}"></script>
<script src="{{ asset('assets/js/swiper.jquery.js') }}"></script>
<script src="{{ asset('assets/js/moment.js') }}"></script>
<script src="{{ asset('assets/js/daterangepicker.js') }}"></script>
<script src="{{ asset('assets/js/simplecalendar.js') }}"></script>
<script src="{{ asset('assets/js/fullcalendar.js') }}"></script>
<script src="{{ asset('assets/js/isotope.pkgd.js') }}"></script>
<script src="{{ asset('assets/js/ajax-pagination.js') }}"></script>
<script src="{{ asset('assets/js/Chart.js') }}"></script>
<script src="{{ asset('assets/js/chartjs-plugin-deferred.js') }}"></script>
<script src="{{ asset('assets/js/circle-progress.js') }}"></script>
<script src="{{ asset('assets/js/loader.js') }}"></script>
<script src="{{ asset('assets/js/run-chart.js') }}"></script>
<script src="{{ asset('assets/js/jquery.magnific-popup.js') }}"></script>
<script src="{{ asset('assets/js/jquery.gifplayer.js') }}"></script>
<script src="{{ asset('assets/js/mediaelement-and-player.js') }}"></script>
<script src="{{ asset('assets/js/mediaelement-playlist-plugin.min.js') }}"></script>

<script src="{{ asset('assets/js/base-init.js') }}"></script>
<script defer src="fonts/fontawesome-all.js"></script>

<script src="{{ asset('assets/Bootstrap/dist/js/bootstrap.bundle.js') }}"></script>
